const fs = require('fs');
const path = require('path');

const CONTEXT_DIR = path.join(__dirname, '..', '.agent', 'context');
const OUTPUT_FILE = path.join(__dirname, '..', 'ZEUZ_FULL_CONTENT.md');

const files = [
    'marketing-strategy.md',
    'business-logic.md',
    'communications.md',
    'tech-stack.json',
    'design-system.json'
];

let fullContent = `# ZEUZ_SUPPLY // FULL SYSTEM CONTENT
**Generated on:** ${new Date().toISOString()}
**Version:** 2.1.0

This document is an autogenerated aggregation of the ".agent" context modules.
It serves as the single source of truth for Business Logic, Design, and Strategy.

---

`;

files.forEach(file => {
    const filePath = path.join(CONTEXT_DIR, file);
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        const ext = path.extname(file);

        fullContent += `\n# MODULE: ${file}\n`;

        if (ext === '.json') {
            try {
                // Try to make JSON more readable by parsing and re-stringifying or just formatting
                const jsonContent = JSON.parse(content);
                fullContent += "```json\n" + JSON.stringify(jsonContent, null, 2) + "\n```\n";
            } catch (e) {
                fullContent += "```json\n" + content + "\n```\n";
            }
        } else {
            fullContent += `\n${content}\n`;
        }
        fullContent += `\n---\n`;
    } else {
        console.warn(`Warning: File not found: ${file}`);
    }
});

fs.writeFileSync(OUTPUT_FILE, fullContent);
console.log(`Successfully generated ${OUTPUT_FILE}`);
