-- Add 'ARCHIVED' to the status CHECK constraint for the batches table
-- First, drop the existing constraint. We need to find its name. 
-- In Supabase/PostgreSQL, it's often autogenerated if not named.
-- Let's try to drop it by name if we can find it, or use a safer approach.

DO $$ 
BEGIN 
    -- Drop the check constraint if it exists. 
    -- Postgres usually names it 'batches_status_check' based on column name.
    ALTER TABLE public.batches DROP CONSTRAINT IF EXISTS batches_status_check;
    
    -- Add the updated constraint
    ALTER TABLE public.batches ADD CONSTRAINT batches_status_check CHECK (status IN ('LIVE', 'TRANSIT', 'TESTING', 'sold_out', 'ARCHIVED'));
END $$;
